settings:
  name: StorageGRID
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    # Remove this comment and uncomment the harmony_enabled line immediately before initial publishing
    # harmony_enabled: true
sidebar:
  entries:
    - title: StorageGRID docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Discover your StorageGRID systems
          url: /task-discover-storagegrid.html
    - title: Manage StorageGRID systems
      entries:
        - title: View your StorageGRID systems
          url: /task-view-storagegrid.html
        - title: Remove StorageGRID systems
          url: /task-remove-storagegrid.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Cloud Manager
  repo: cloud-manager-family
  sidebar_label: All Cloud Manager documentation
homepage:
  tiles:
    - title: Get started
      links:
        - title: Discover your StorageGRID systems
          url: task-discover-storagegrid.html
    - title: Manage StorageGRID systems
      links:
        - title: View your StorageGRID systems
          url: task-view-storagegrid.html
        - title: Use NetApp data services with StorageGRID
          url: task-enable-data-services.html
        - title: Remove StorageGRID
          url: task-remove-storagegrid.html
    - title: More information
      links:
        - title: StorageGRID documentation for management outside of Cloud Manager
          url: https://docs.netapp.com/us-en/storagegrid-116/
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
