---
sidebar: sidebar
permalink: reference-known-issues.html
keywords: issues, known issues, bugs, errors
summary: Known issues identify problems that might prevent you from using this release of the product successfully.
---

= Known issues
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Known issues identify problems that might prevent you from using this release of the product successfully.

== Updated display names don't appear in BlueXP

If you use the rename procedure to define a new display name for a site or grid, the new display name isn't reflected in the BlueXP working environment. The working environment continues to show the system name and not the new display name.

== Error when filtering alerts

When using the advanced view, filtering the contents of the Alerts page results in an error.

== Error when editing grid federation connection

When using the advanced view, you might encounter a gateway timeout error when editing a grid federation connection.

== Error after page reload

If a page reloads when using the advanced view, the page might fail to reload and an error displays in BlueXP. You might encounter this issue in the following scenarios:

* You manually reload a page from your web browser.
* Grid Manager automatically reloads a page, which can happen when you update a management certificate or rename the grid.

If you experience this issue, you'll need to manually re-enter the working environment from the canvas and select the advanced view again.