---
sidebar: sidebar
permalink: task-enable-data-services.html
keywords: storagegrid, cloud sync, cloud backup, backup, back up data, tier data, data tiering, tiering to storagegrid, tiering
summary: After you discover a StorageGRID system in BlueXP, you can use NetApp's data services for backups, data tiering, and data synchronization.
---

= Use NetApp data services with StorageGRID
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
After you discover a StorageGRID system in BlueXP, you can use NetApp's data services for backups, data tiering, and data synchronization.

* Use BlueXP backup and recovery to back up data from your on-premises ONTAP systems to object storage in your NetApp StorageGRID systems.
+
To get started, go to the BlueXP canvas and drag and drop an on-premises ONTAP working environment on your StorageGRID working environment.
+
https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html[Learn more about backing up on-premises ONTAP data to StorageGRID^]

* Use BlueXP tiering to automatically tier inactive data from on-premises ONTAP clusters to StorageGRID.
+
To get started, go to the BlueXP canvas and drag and drop an on-premises ONTAP working environment on your StorageGRID working environment.
+
https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-storagegrid.html[Learn more about tiering data from on-premises ONTAP clusters to StorageGRID^]

* Use BlueXP copy and sync to synchronize data to or from a StorageGRID system.
+
To get started, go to the BlueXP canvas and drag and drop the source working environment on the target working environment. StorageGRID can be either the source or target.
+
https://docs.netapp.com/us-en/bluexp-copy-sync/index.html[Learn more about BlueXP copy and sync^]
