---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, storagegrid
summary: Learn what's new with managing StorageGRID systems in BlueXP.
---

= What's new with StorageGRID management
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new with managing StorageGRID systems in BlueXP.

// tag::whats-new[]
== 7 August 2024

=== New advanced view

Grid Manager is now available in BlueXP starting with StorageGRID 11.8. When you manage your StorageGRID system from BlueXP, you can use the familiar Grid Manager interface and BlueXP services that provide data mobility and data protection.

https://docs.netapp.com/us-en/bluexp-storagegrid/task-administer-storagegrid.html[Learn how to administer StorageGRID using the advanced view].

=== Ability to review and approve StorageGRID management interface certificate

When first connecting to a StorageGRID system using BlueXP, you now have the ability to review and approve the existing StorageGRID management interface certificate or use a different one. 

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html[Learn how to review and aopprove the server certificate during system discovery.]

== 18 September 2022

=== Support for StorageGRID

You can now discover your StorageGRID systems directly from BlueXP. Discovering StorageGRID provides you with a complete view of data across your hybrid multicloud.
// end::whats-new[]
